title: George Lee
logo: pic/Picture2.jpg
theme: jekyll-theme-minimal

{
  "Education"
  [{Master of Information Technology | University of Technology Sydney},
  {Bachelor of Finance and Banking | Shin Chien University}
  ]
}


