title: George Lee
logo: pic/Picture2.jpg
theme: jekyll-theme-minimal

Education: 
Master of Information Technology | University of Technology Sydney
Bachelor of Finance and Banking | Shin Chien University

Tools:
Tableau 
Power BI                                                                  
SQL
Python
Alteryx

Skills:
Data Analytics
Data Visualisation
Actionable Recommendations
Strategic Planning
Collaborative Work
Problem Resolution
