title: George Lee
logo: pic/Picture2.jpg
social-network-links:
  email: "georgelee0322@gmail.com"
  tableau: "https://public.tableau.com/app/profile/george.lee0322/vizzes"
share-links-active:
  email: true
  tableau: true


theme: jekyll-theme-minimal
